syntax enable
set expandtab
set guicursor=
set relativenumber
set nu
set tabstop=4 softtabstop=4
set shiftwidth=4
set smartindent
set noswapfile

filetype indent on
set autoindent

let python_highlight_all = 1

