set guicursor=
set relativenumber
set nu
set tabstop=4 softtabstop=4
set shiftwidth=4
set smartindent
set noswapfile



" Give more space for displaying messages.
set cmdheight=2

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=50


" - plugins
call plug#begin('~/.vim/plugged')
        Plug 'scrooloose/syntastic'
        Plug 'ervandew/supertab'
        Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
        Plug 'scrooloose/nerdtree'
call plug#end()


" Nerd Tree
:map <C-o> :NERDTree


" Syntastic 
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
